### PR TITLE
new name #3

### PR DESCRIPTION
**Pull request by cli0**

### CODE REVIEW

**Comment by xp4xbox** [comment]
I'd like the entire thing to be different.

**Comment by cli0** [comment]
by entire thing, do you mean the title to be completely different or the whole html page?

**Comment by xp4xbox** [comment]
The title.

**Comment by xp4xbox** [comment]
@cli0 if you cannot find one that is ok. I can simply mark this as invalid.

**Comment by cli0** [comment]
i'm just trying to think of a catchy title, what about this?

**Comment by xp4xbox** [comment]
What about `Turn up the challenge with this brand new mode!`

**Pull request merged**
